name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Start
      run: |
         echo 666
         sudo docker rmi $(docker images -q)
         sudo curl https://nyat-static.globalslb.net/natfrp/client/0.45.0-sakura-3.1/frpc_linux_amd64 >$HOME/frpc
         sudo apt install ttyd -y
         sudo chmod a+x $HOME/frpc
         sudo $HOME/frpc -f 47380d154cf02411:6176808 &
         #sudo ttyd -p 1234 bash &
         sudo sshd -E -p 1234
         cd $HOME
         curl -sL https://git.io/file-transfer | sh
    - name: StartLoop
      run: |
        sleep 9999
        sleep 9999
