name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    #- name: Get SDK Code
    #  uses: curoky/cleanup-disk-action@v2.0

    - name: Start
      run: |
         sudo docker rmi $(docker images -q)
         sudo curl https://nyat-static.globalslb.net/natfrp/client/0.39.1-sakura-1.1/frpc_linux_amd64 >$HOME/frpc
         sudo apt install openssh-server -y
         sudo chmod a+x $HOME/frpc
         echo "runner:1"|sudo chpasswd
         sudo $HOME/frpc -f 47380d154cf02411:2918234 &
         sudo sshd -p 1234 &
         cd $HOME
         curl -sL https://git.io/file-transfer | sh

    - name: StartLoop
      run: |
        sleep 9999
        sleep 9999
