name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get SDK Code
      uses: curoky/cleanup-disk-action@v2.0
    
    - name: Start
      run: source postrun.sh
    
    - name: Daemon
      run: source postrun1.sh
    
    - name: Store file partition
      uses: actions/upload-artifact@v1
      with:
        name: SDKpkg
        path: /file/
