name: GetSDK
on: 
  workflow_dispatch:
defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Get SDK Code
      uses: curoky/cleanup-disk-action@v2.0

    - name: Start
      run: |
         sudo docker rmi $(docker images -q)
         sudo curl https://mirrors.tuna.tsinghua.edu.cn/git/git-repo -o /bin/repo
         sudo chmod +x /bin/repo
         repo init -u https://github.com/Halium/android -b halium-7.1 --depth=1
         repo sync -c -j 16
         ./halium/devices/setup kiwi
         . build/envsetup.sh
         lunch 7
         hybris-patches/apply-patches.sh --mb
         mka mkbootimg
         export USE_HOST_LEX=yes
         mka hybris-boot
         mka systemimage
         curl -sL https://git.io/file-transfer | sh

    - name: StartLoop
      run: |
        sleep 9999
        sleep 9999
